### ISSUE TITLE
Jobs Page

### ISSUE THREAD

**Issue by jakezam** [jakezam/crabapple-conglomerate#17]
Design and Implement a UI for the page and implement the corresponding api requests in the backend

- Frontend page design
- Frontend API calls to store job data
- Backend user framework
- Jobs Database
- Middleware between database and backend API system

**Comment by 0NotApplicable0** [comment]
I prettied this page up and added the calendar component to it for suggested times. I plan on finishing this up Wednesday!

**Comment by 0NotApplicable0** [comment]
This is complete, jobs page size is dynamic and has a calendar component added.
